FROM debian:12.12-slim

WORKDIR /app

ARG APK_MIRROR_ARG
ARG APT_MIRROR_ARG

RUN useradd -m -s /bin/bash appuser

RUN if [ -n "$APK_MIRROR_ARG" ]; then \
        sed -i -E "s@https?://(deb|security).debian.org@http://${APK_MIRROR_ARG}@g" /etc/apt/sources.list.d/debian.sources; \
    elif [ -n "$APT_MIRROR_ARG" ]; then \
        sed -i -E "s@https?://(deb|security).debian.org@http://${APT_MIRROR_ARG#*://}@g" /etc/apt/sources.list.d/debian.sources; \
    fi && \
    apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY docker/fonts-weknora-cjk.conf /etc/fonts/conf.d/64-weknora-cjk.conf

RUN if [ -n "$APK_MIRROR_ARG" ]; then \
        sed -i -E "s@https?://(deb|security).debian.org@http://${APK_MIRROR_ARG}@g" /etc/apt/sources.list.d/debian.sources; \
    fi && \
    if [ -n "$APT_MIRROR_ARG" ]; then \
        sed -i -E "s@https?://[^ /]+@${APT_MIRROR_ARG}@g" /etc/apt/sources.list.d/debian.sources; \
    fi && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential postgresql-client default-mysql-client tzdata sed curl bash vim wget \
        libsqlite3-0 \
        python3 python3-pip python3-dev libffi-dev libssl-dev \
        nodejs npm \
        gosu \
        ffmpeg fonts-noto-cjk libreoffice-calc libreoffice-impress libreoffice-writer && \
    fc-cache -f && \
    python3 -m pip install --break-system-packages --upgrade pip setuptools wheel && \
    chown -R appuser:appuser /home/appuser && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /data/files && \
    chown -R appuser:appuser /app /data/files
